require:
  - solidus_dev_support/rubocop

Style/ExpandPathArguments:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/HookArgument:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Rails/HttpStatus:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false
