version: 2.1

orbs:
  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile

commands:
  bundle:
    description: 'Install and cache gems'
    steps:
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "solidus_graphql_api.gemspec" }}-{{ checksum "Gemfile" }}
            - v1-bundle-{{ checksum "solidus_graphql_api.gemspec" }}
            - v1-bundle-
      - run: bundle check || bundle install
      - save_cache:
          key: v1-bundle-{{ checksum "solidus_graphql_api.gemspec" }}-{{ checksum "Gemfile" }}
          paths:
            - ~/project/vendor/bundle

jobs:
  verify-schema-updated:
    docker:
      - image: circleci/ruby:2.5.6-node
        environment:
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      - bundle
      - run:
          name: Check if Schema is up-to-date
          command: |
            mv schema.graphql old_schema.graphql
            bundle exec rake schema:idl
            diff old_schema.graphql schema.graphql

  run-specs-with-postgres:
    executor: solidusio_extensions/postgres
    steps:
      - checkout
      - solidusio_extensions/run-tests-solidus-current
      - solidusio_extensions/store-test-results
      - solidusio_extensions/run-tests-solidus-master
      - solidusio_extensions/store-test-results
      - run:
          name: Install & Upload test coverage to Code Climate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter format-coverage -t simplecov -o ./coverage/codeclimate.json
            ./cc-test-reporter upload-coverage

  run-specs-with-mysql:
    executor: solidusio_extensions/mysql
    steps:
      - checkout
      - solidusio_extensions/run-tests-solidus-current
      - solidusio_extensions/store-test-results
      - solidusio_extensions/run-tests-solidus-master
      - solidusio_extensions/store-test-results


  schema-breaking-change-detection:
    docker:
      - image: circleci/ruby:2.5.6-node
    steps:
      - checkout
      - run:
          name: Install GraphQL::SchemaComparator
          command: gem install graphql-schema_comparator
      - run:
          name: Schema Breaking Change detection
          command: rm Gemfile && schema_comparator verify "`git show origin/master:schema.graphql`" schema.graphql

  lint-code:
    executor: solidusio_extensions/sqlite-memory
    steps:
      - solidusio_extensions/lint-code

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - verify-schema-updated
      - schema-breaking-change-detection:
          requires:
            - verify-schema-updated
      - run-specs-with-postgres:
          requires:
            - verify-schema-updated
      - run-specs-with-mysql:
          requires:
            - verify-schema-updated
      - lint-code

  "Weekly run specs against master":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - run-specs-with-postgres
      - run-specs-with-mysql
